FROM ruby:2.7

RUN apt-get update -qq && apt-get install -y build-essential libpq-dev nodejs

RUN mkdir /rails-api
WORKDIR /rails-api

COPY Gemfile Gemfile.lock ./
RUN bundle install
ADD . .
EXPOSE 3000


